apiVersion: v1
kind: ConfigMap
metadata:
  name: alertmanager-config
  namespace: travelmemory
  labels:
    app: alertmanager
    component: monitoring
data:
  alertmanager.yml: |
    global:
      resolve_timeout: 5m

    route:
      group_by: ['alertname', 'cluster', 'service']
      group_wait: 10s
      group_interval: 10s
      repeat_interval: 12h
      receiver: 'web.hook'
      routes:
        - match:
            severity: critical
          receiver: 'critical-alerts'
        - match:
            severity: warning
          receiver: 'warning-alerts'

    receivers:
      - name: 'web.hook'
        webhook_configs:
          - url: 'http://localhost:5001/'

      - name: 'critical-alerts'
        webhook_configs:
          - url: 'http://localhost:5001/'
        # Uncomment and configure for email notifications
        # email_configs:
        #   - to: 'admin@example.com'
        #     from: 'alertmanager@example.com'
        #     smarthost: 'smtp.gmail.com:587'
        #     auth_username: 'alertmanager@example.com'
        #     auth_password: 'your-password'

      - name: 'warning-alerts'
        webhook_configs:
          - url: 'http://localhost:5001/'
        # Uncomment and configure for Slack notifications
        # slack_configs:
        #   - api_url: 'https://hooks.slack.com/services/YOUR/WEBHOOK/URL'
        #     channel: '#alerts'
        #     title: '{{ .GroupLabels.alertname }}'
        #     text: '{{ range .Alerts }}{{ .Annotations.description }}{{ end }}'

    inhibit_rules:
      - source_match:
          severity: 'critical'
        target_match:
          severity: 'warning'
        equal: ['alertname', 'instance']
