apiVersion: v1
kind: Service
metadata:
  name: alertmanager-service
  namespace: travelmemory
  labels:
    app: alertmanager
    component: monitoring
spec:
  type: NodePort
  selector:
    app: alertmanager
  ports:
  - port: 9093
    targetPort: 9093
    nodePort: 30093
    name: alertmanager
