apiVersion: v1
kind: ConfigMap
metadata:
  name: grafana-datasources-config
  namespace: travelmemory
  labels:
    app: grafana
    component: monitoring
data:
  datasources.yaml: |
    apiVersion: 1
    
    datasources:
      - name: Prometheus
        type: prometheus
        access: proxy
        url: http://prometheus-service:9090
        isDefault: true
        editable: true
        jsonData:
          timeInterval: 5s
      
      - name: Loki
        type: loki
        access: proxy
        url: http://loki-service:3100
        editable: true
        jsonData:
          maxLines: 1000
