apiVersion: v1
kind: Service
metadata:
  name: grafana-service
  namespace: travelmemory
  labels:
    app: grafana
    component: monitoring
spec:
  type: NodePort
  selector:
    app: grafana
  ports:
  - port: 3000
    targetPort: 3000
    nodePort: 30092
    name: grafana
