apiVersion: v1
kind: Service
metadata:
  name: loki-service
  namespace: travelmemory
  labels:
    app: loki
    component: logging
spec:
  type: NodePort
  selector:
    app: loki
  ports:
  - port: 3100
    targetPort: 3100
    nodePort: 30310
    name: http
