apiVersion: v1
kind: Service
metadata:
  name: node-exporter-service
  namespace: travelmemory
  labels:
    app: node-exporter
    component: monitoring
spec:
  type: NodePort
  selector:
    app: node-exporter
  ports:
  - port: 9100
    targetPort: 9100
    nodePort: 30100
    name: metrics
