apiVersion: v1
kind: ConfigMap
metadata:
  name: prometheus-rules
  namespace: travelmemory
  labels:
    app: prometheus
    component: monitoring
data:
  alerts.yml: |
    groups:
      - name: kubernetes_alerts
        interval: 30s
        rules:
          # High CPU usage alert
          - alert: HighCPUUsage
            expr: 100 - (avg by(instance) (rate(node_cpu_seconds_total{mode="idle"}[5m])) * 100) > 80
            for: 5m
            labels:
              severity: warning
            annotations:
              summary: "High CPU usage detected"
              description: "CPU usage is above 80% on instance {{ $labels.instance }}"

          # High memory usage alert
          - alert: HighMemoryUsage
            expr: (1 - (node_memory_MemAvailable_bytes / node_memory_MemTotal_bytes)) * 100 > 85
            for: 5m
            labels:
              severity: warning
            annotations:
              summary: "High memory usage detected"
              description: "Memory usage is above 85% on instance {{ $labels.instance }}"

          # Pod restart alert
          - alert: PodRestartLoop
            expr: rate(kube_pod_container_status_restarts_total[15m]) > 0
            for: 5m
            labels:
              severity: warning
            annotations:
              summary: "Pod restart loop detected"
              description: "Pod {{ $labels.pod }} in namespace {{ $labels.namespace }} is restarting frequently"

          # High disk usage alert
          - alert: HighDiskUsage
            expr: (node_filesystem_avail_bytes{mountpoint="/"} / node_filesystem_size_bytes{mountpoint="/"}) * 100 < 15
            for: 5m
            labels:
              severity: critical
            annotations:
              summary: "High disk usage detected"
              description: "Disk usage is above 85% on instance {{ $labels.instance }}"

          # Pod down alert
          - alert: PodDown
            expr: kube_pod_status_phase{phase!="Running"} == 1
            for: 5m
            labels:
              severity: critical
            annotations:
              summary: "Pod is down"
              description: "Pod {{ $labels.pod }} in namespace {{ $labels.namespace }} is not running"

          # Application error rate alert
          - alert: HighErrorRate
            expr: rate(http_requests_total{status=~"5.."}[5m]) > 10
            for: 5m
            labels:
              severity: warning
            annotations:
              summary: "High error rate detected"
              description: "Application error rate is above threshold: {{ $value }} errors/sec"

          # Slow response time alert
          - alert: SlowResponseTime
            expr: histogram_quantile(0.95, rate(http_request_duration_seconds_bucket[5m])) > 1
            for: 5m
            labels:
              severity: warning
            annotations:
              summary: "Slow response time detected"
              description: "95th percentile response time is above 1s"
