apiVersion: v1
kind: Service
metadata:
  name: promtail-service
  namespace: travelmemory
  labels:
    app: promtail
    component: logging
spec:
  type: ClusterIP
  selector:
    app: promtail
  ports:
  - port: 9080
    targetPort: 9080
    name: http
