# ==============================================
# KUBERNETES LEARNING: SECRETS
# File: 02-secrets.yaml
# ==============================================

# WHAT IS A SECRET?
# - Stores sensitive data (passwords, API keys, tokens)
# - Data is Base64 encoded (NOT encrypted by default!)
# - Can be mounted as files or environment variables
# - Never commit secrets to git in production (use sealed-secrets, external-secrets, or vault)

apiVersion: v1
kind: Secret

metadata:
  name: mongodb-secret
  namespace: travelmemory  # Lives in our namespace
  labels:
    app: travelmemory
    component: database

# type: Different secret types have different behavior
# - Opaque: generic key-value pairs (what we're using)
# - kubernetes.io/tls: TLS certificates
# - kubernetes.io/dockerconfigjson: Docker registry credentials

type: Opaque

# stringData: Automatically base64 encodes the values
# - Use this when writing YAML files
# - Alternative: use "data" with pre-encoded base64 values

stringData:
  # MongoDB root username
  # Referenced as: MONGO_ROOT_USERNAME
  username: admin
  
  # MongoDB root password
  # Referenced as: MONGO_ROOT_PASSWORD  
  password: password123
  
  # Database name
  # Referenced as: MONGO_INITDB_DATABASE
  database: travelmemory

# ==============================================
# HOW TO USE THIS SECRET:
# ==============================================
# 1. Reference in Deployments as environment variables
# 2. Example:
#    env:
#    - name: MONGO_PASSWORD
#      valueFrom:
#        secretKeyRef:
#          name: mongodb-secret
#          key: password
#
# 3. Or mount as files in the pod
#
# 4. Base64 is NOT encryption! Anyone with access can decode.
#    For production, use:
#    - sealed-secrets operator
#    - external-secrets operator  
#    - HashiCorp Vault
#    - AWS Secrets Manager, etc.

# ==============================================
# KEY LEARNING POINTS:
# ==============================================
# 1. Secrets store sensitive data
# 2. Base64 encoded (not encrypted)
# 3. Can be injected as env vars or mounted as files
# 4. Must exist before resources that reference it
# 5. Never commit real secrets to git!

